277: Fetch third party users by email
supertokens/supertokens-node pull request #161
Opened 2021-08-06 00:53 UTC by dulowski-marek

## Summary of change
This implements get users by email endpoint for ThirdParty. It also implements a function in ThirdPartyEmailPassword since the two are bound by common types (interfaces).

## Related issues
- https://github.com/supertokens/supertokens-core/issues/277

## Test Plan
1. Test API validation
2. Test that API output is correct

## Documentation changes
- FDI change

## Checklist for important updates
- [ ] Changelog has been updated
- [x] `coreDriverInterfaceSupported.json` file has been updated (if needed)
   - Along with the associated array in `lib/ts/version.ts`
- [x] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `package.json`
   - In `package-lock.json`
   - In `lib/ts/version.ts`
- [x] Had run `npm run build-pretty`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] FDI change

2021-08-09 07:57 UTC, dulowski-marek commented
The exposed API endpoint has to be removed, since we only want to expose a function.

2021-08-13 10:06 UTC, rishabhpoddar requested changes

2021-08-13 10:06 UTC, rishabhpoddar commented on lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.ts
> +        return this.recipeImplementation.getThirdPartyUsersByEmail(input);
If we are going with my previous suggestion of creating one `getUsersByEmail` function in `ThirdPartyRecipeInterface` (it should actually be called `ThirdPartyEmailPasswordRecipeInterface` - my bad), then this function would need to be changed to filter out the users that are not third party users.

2021-08-13 10:06 UTC, rishabhpoddar commented on lib/ts/recipe/thirdpartyemailpassword/types.ts
> +    getThirdPartyUsersByEmail(input: { email: string }): Promise<ThirdPartyUser[]>;
See comment in `lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts`

2021-08-13 10:06 UTC, rishabhpoddar commented on lib/ts/utils.ts
> +export function frontendHasInterceptor(req: Request): boolean {
This should not be in the PR. But it's there since the base was wrong. So please correct.

2021-08-13 10:06 UTC, rishabhpoddar commented on lib/ts/version.ts
> +export const version = "7.0.0";
Still version 6.1.0 since this is not a breaking change.

2021-08-13 10:06 UTC, rishabhpoddar commented on package.json
> +    "version": "7.0.0",
Should be 6.1.0

2021-08-13 10:06 UTC, rishabhpoddar commented on test/sessionExpress.test.js
> +    it("check session verify for with session optional and no rid pass", async function () {
All these tests should not be there since they are for 7.0

2021-08-13 10:06 UTC, rishabhpoddar commented on test/thirdparty/getUsersByEmailFeature.test.js
> +        thirdPartyUsers.forEach((user) => {
Consider checking element [0] explicitly first, and then element [1]. I don't think the ordering should change? I'm not sure..

2021-08-13 10:07 UTC, rishabhpoddar commented
- No changes are required to FDI
- Changes to the docs will be required:
   - Explaining this new function in the node SDK docs + the recipe docs (maybe?)
   - Changing the interface of the recipe functions in the nodeJS docs.

2021-08-21 06:22 UTC, rishabhpoddar commented
Closing since base branch is 7.0, but it should be 6.1

2021-08-21 06:22 UTC, closed without merging

2021-08-21 06:55 UTC, rishabhpoddar commented
See https://github.com/supertokens/supertokens-node/pull/165 instead.