refactor: code review changes
supertokens/supertokens-node pull request #322
Opened 2022-06-02 11:00 UTC by bhumilsarvaiya

## Change related to the following PR review:

- https://github.com/supertokens/supertokens-node/pull/274#discussion_r887807403

## Related PR

-   #274

2022-06-02 11:12 UTC, rishabhpoddar requested changes

2022-06-02 11:12 UTC, rishabhpoddar commented on lib/ts/recipe/thirdpartyemailpassword/emaildelivery/services/backwardCompatibility/index.ts
> +                      createAndSendCustomEmail: async (user: EmailPasswordUser, link: string, userContext: any) => {
You need to build project as well

2022-06-02 12:47 UTC, bhumilsarvaiya commented on lib/ts/recipe/thirdpartyemailpassword/emaildelivery/services/backwardCompatibility/index.ts
> +                      createAndSendCustomEmail: async (user: EmailPasswordUser, link: string, userContext: any) => {
I did, no changes

2022-06-02 13:12 UTC, rishabhpoddar requested changes

2022-06-02 13:12 UTC, rishabhpoddar commented on lib/ts/recipe/thirdpartyemailpassword/emaildelivery/services/backwardCompatibility/index.ts
> +                      createAndSendCustomEmail: async (user: EmailPasswordUser, link: string, userContext: any) => {
- Add a test to sign up with third party and then send them an email verification email (this should fail)
- We have to create an email verification backwards compatibility service as well (and then the above test should pass).

2022-06-06 11:04 UTC, rishabhpoddar requested changes

2022-06-06 11:04 UTC, rishabhpoddar commented on test/thirdpartyemailpassword/emailverify.test.js
> +    it("test that providing your own email callback and make sure it is called (thirdparty user)", async function () {
We need to add more tests like:
- Emailpassword recipe:
   - creating email password user and doing reset password and email verification email
   - Trying to send reset password to non existent user should not call your callback
- Third party recipe:
   - creating third party user and sending email verification to them.
- Third party email password recipe:
   - creating email password user and doing reset password and email verification email
   - creating third party user and doing email verification email
   - creating third party user and doing password reset -> should not call the callback
   - Trying to send reset password to non existent user should not call your callback.
- Passwordless recipe:
   - Sending email and SMS for login should call callback
-  Third party passwordless recipe:
   - Sending email and SMS for passwordless login should call callback
   - Email verification email for third party user -> should call callback
   - Email verification for passwordless user -> should not call callback

2022-06-08 16:09 UTC, rishabhpoddar approved these changes

2022-06-09 05:47 UTC, merged