feat: userIdMapping
supertokens/supertokens-node pull request #359
Opened 2022-07-25 10:41 UTC by jscyo

## Summary of change

(A few sentences about this PR)

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `add-ts-no-check.js` file to include that
-   [ ] If added a new recipe / api interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If added a new recipe, then make sure to expose it inside the recipe folder present in the root of this repo. We also need to expose its types.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2022-07-26 08:10 UTC, jscyo commented
## Feedback
EmailPassword recipe feedback:
- [ ] SignIn function should also call recipe mapping
- [ ] userContext should be passed to the recipe mapping functions
- [ ] we should store userIdMapping in userContext, so if multiple apis are calling each other there wont be duplicate calls
- [ ] the userIdMapping recipe functions should check the userContext to reduce clutter when the functions are being called in the recipe
- [ ] resetPasswordUsingToken function does should also call userIdMapping
- [ ] Implement userId mapping in emailverification functions

2022-07-26 12:54 UTC, rishabhpoddar requested changes

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/useridmapping/index.ts
> +}
No need for this enum type

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/useridmapping/utils.ts
> +}
No need

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/emailpassword/recipeImplementation.ts
> +            if (response.status === "OK") {
```suggestion
            if (response.status === "OK" && response.userId !== undefined) {
```

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/useridmapping/types.ts
> +        userIdType?: "SUPERTOKENS" | "EXTERNAL" | "ANY";
userContext missing

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/useridmapping/types.ts
> +        externalUserIdInfo: string | null;
userContext missing

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/useridmapping/index.ts
> +    }
need to expose all the recipe interface functions

2022-07-26 12:54 UTC, rishabhpoddar commented on lib/ts/recipe/emailverification/recipeImplementation.ts
>              | {
Undo all the changes for email verificaiton recipe

2022-07-26 13:23 UTC, rishabhpoddar approved these changes

2022-07-27 10:34 UTC, rishabhpoddar requested changes

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/recipe/useridmapping/recipe.ts
> +let isUserIdMappingRecipeInitialized = false;
You don't need this.. just do Recipe.instance === undefined instead

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/recipe/passwordless/recipeImplementation.ts
> +                if (isUserIdMappingRecipeInitialized) {
why twice?

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/recipe/thirdparty/recipeImplementation.ts
> +            if (!response.createdNewUser) {
Remove this check

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/recipe/thirdparty/recipeImplementation.ts
> +            }
You have not mapped the external userID back

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/supertokens.ts
> +                                        recipeId: userObj.recipeId,
```suggestion
                                        ...userObj,
```

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/supertokens.ts
> +                }
What is this for?

2022-07-27 10:34 UTC, rishabhpoddar commented on lib/ts/supertokens.ts
> +                }
else???

2022-07-27 11:20 UTC, rishabhpoddar requested changes

2022-07-27 11:20 UTC, rishabhpoddar commented on lib/ts/supertokens.ts
> +            let doesUserIdMappingExist = false;
Call this variable somethign better

2022-07-27 11:24 UTC, rishabhpoddar approved these changes

2022-07-29 09:51 UTC, rishabhpoddar approved these changes

2022-08-11 11:04 UTC, rishabhpoddar approved these changes

2022-08-11 11:08 UTC, merged