feat: access token to jwt base
supertokens/supertokens-node pull request #531
Opened 2023-03-30 13:42 UTC by porcellus

## Summary of change

- Rename sessionData to sessionDataFromDatabase
- Adding ...WithoutRequestResponse variants for create/refresh/getSession
- CDI update

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [x] Changelog has been updated
-   [x] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [x] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [x] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [x] Had run `npm run build-pretty`
-   [x] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [x] If have added a new web framework, update the `add-ts-no-check.js` file to include that
-   [x] If added a new recipe / api interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [x] If added a new recipe, then make sure to expose it inside the recipe folder present in the root of this repo. We also need to expose its types.

## Remaining TODOs for this PR

-   [ ] create new version branch
- [x] Add  `useStaticSigningKey` to createJWT in session index file
- [x] Update CDI to 2.21
- [ ] You should add a test on the frontend SDK related to the new exposeAccessTokenToTheFrontend boolean. For example
   - We want to make sure that refreshing still works in cookie based even if the access token is exposed to the frontend.
   - We want to check that getting the access token payload still works well, and that you get the full payload on the frontend - json object containing sub, refreshTokenHash1, iat + user's custom payload.

2023-04-23 13:29 UTC, rishabhpoddar requested changes

2023-04-23 13:29 UTC, rishabhpoddar commented on CHANGELOG.md
> +```
this section will go away cause we will add the issuer by default - as discussed?

2023-04-26 09:21 UTC, KShivendu commented on CHANGELOG.md
> +import Session from "supertokens-auth-react/recipe/session";
auth-react?

2023-04-27 12:43 UTC, KShivendu commented on lib/ts/recipe/session/index.ts
> +        await refreshSessionInRequest({ res, req, userContext, config, recipeInterfaceImpl });
Shouldn't this return as well?

2023-05-04 15:21 UTC, merged