feat: added `network_interceptor` hook
supertokens/supertokens-node pull request #738
Opened 2023-11-09 06:36 UTC by IamMayankThakur

this hook can be used to capture all requests sent to the core

## Summary of change

(A few sentences about this PR)

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] If new thirdparty provider is added,
    -   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function.
    -   [ ] add an icon on the user management dashboard.
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `add-ts-no-check.js` file to include that
-   [ ] If added a new recipe / api interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If added a new recipe, then make sure to expose it inside the recipe folder present in the root of this repo. We also need to expose its types.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-11-10 06:01 UTC, rishabhpoddar requested changes

2023-11-10 06:01 UTC, rishabhpoddar commented on lib/ts/querier.ts
> +                            params: undefined,
```suggestion
```

2023-11-10 07:16 UTC, IamMayankThakur commented on lib/ts/types.ts
> +    params?: Record<string, boolean | number | string | undefined>;
To align the types with the existing type for `params` in the querier.

https://github.com/supertokens/supertokens-node/blob/e9ba8f8d4906387bce77d3187af694aa659bed78/lib/ts/querier.ts#L182

2023-11-11 07:33 UTC, rishabhpoddar requested changes

2023-11-11 07:33 UTC, rishabhpoddar commented on lib/ts/recipe/session/sessionFunctions.ts
> +    userContext: any,
should be the last param, and non optional.. please check in all places! So you can remove the `= {}` from the other two params of this function, and manually check all places where this function is being called to make sure that the params are correctly provided to the function call.

2023-11-11 07:33 UTC, rishabhpoddar commented on lib/ts/recipe/session/sessionFunctions.ts
> +    userContext: any,
should be the last param.. and non optional.

2023-11-11 07:33 UTC, rishabhpoddar commented on lib/ts/recipe/session/sessionFunctions.ts
> +    userContext: any,
should be the last param.. and non optional

2023-11-13 08:24 UTC, rishabhpoddar requested changes

2023-11-13 08:24 UTC, rishabhpoddar commented on lib/ts/recipe/session/sessionFunctions.ts
> +    revokeAcrossAllTenants: boolean,
```suggestion
    tenantId: string | undefined,
    revokeAcrossAllTenants: boolean | undefined,
```

2023-11-13 08:24 UTC, rishabhpoddar commented on lib/ts/recipe/session/sessionFunctions.ts
> +    fetchAcrossAllTenants: boolean,
```suggestion
    tenantId: string | undefined,
    fetchAcrossAllTenants: boolean | undefined,
```

2023-11-13 09:59 UTC, rishabhpoddar approved these changes

2023-11-13 10:00 UTC, merged