fix(normaliseUrlDomain): allow custom url scheme
supertokens/supertokens-node pull request #796
Opened 2024-02-27 13:45 UTC by zaosoula

## Summary of change
Refactor the code of normaliseUrlDomainOrThrowError to accept schemes other than http://, https://, supertokens://
(A few sentences about this PR)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] If new thirdparty provider is added,
    -   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function.
    -   [ ] add an icon on the user management dashboard.
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `add-ts-no-check.js` file to include that
-   [ ] If added a new recipe / api interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If added a new recipe, then make sure to expose it inside the recipe folder present in the root of this repo. We also need to expose its types.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2024-02-27 13:49 UTC, zaosoula commented
@rishabhpoddar Here is the pr, unfortunatly I'm unable to launch the test env for now, so if you can give it a try

2024-02-27 13:53 UTC, rishabhpoddar commented
@zaosoula i'll probably try it out later today or sometime this week. In the meantime, you can use your forked version of the sdk instead of the one from npm in your app and see if it works well. Also, you may have to make a similar change to the frontend sdk as well cause that too has the same normalised domain class

2024-02-28 08:09 UTC, rishabhpoddar requested changes

2024-02-28 08:09 UTC, rishabhpoddar commented on lib/ts/normalisedURLDomain.ts
>  function normaliseURLDomainOrThrowError(input: string, ignoreProtocol = false): string {
```suggestion
function normaliseURLDomainOrThrowError(input: string): string {
```

2024-02-28 08:09 UTC, rishabhpoddar commented on lib/ts/normalisedURLDomain.ts
>  function normaliseURLDomainOrThrowError(input: string, ignoreProtocol = false): string {
Not needed since we are not recursing anymore

2024-02-28 08:09 UTC, rishabhpoddar commented on lib/ts/normalisedURLDomain.ts
>          if (ignoreProtocol) {
this if block will never be true so can be removed.

2024-02-28 08:09 UTC, rishabhpoddar commented on lib/ts/normalisedURLDomain.ts
> +    if (input.match(/^[^:]:\/\//)) {
im not sure if this regex is correct. Cause if i do `example.com".match(/^[^:]:\/\//)`, it returns null. But we want it to come in the if block in this case. Am i missing something?

2024-04-11 09:52 UTC, rishabhpoddar commented
Hey @ellipsis, give me a code review

2024-06-03 16:57 UTC, zaosoula commented
Hey https://github.com/ellipsis, give me a code review

2024-09-03 10:25 UTC, closed without merging