feat: Add passkeys support
supertokens/supertokens-node pull request #942
Opened 2024-10-10 14:23 UTC by coolbueb

## Summary of change

Add passkeys support 

## Related issues

-   [Core Repo Passkeys](https://github.com/supertokens/supertokens-core/issues/1046)

## Test Plan

- Mock core API calls
- Add tests for each method individually

More details here: https://docs.google.com/document/d/1G7tO9_dSNi8wur3ajGg4pq-wiHatKDbHv2sBt-uSbQg/edit

2024-10-10 18:12 UTC, rishabhpoddar requested changes

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +// todo update this ???
```suggestion
```

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        password: string;
```suggestion
```

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        session: SessionContainerInterface | undefined;
```suggestion
```

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        status: "OK";
Are there any failure cases in this API?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +    signInPasskeyOptions(input: {
why do we need this function?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        email: string | undefined;
do we need an email here? Given that the first step in signing up is to generate a passkeyoptions, and that function already takes in an email?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +            name: string;
where are we getting thee name from?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +            id: string;
where are we getting the id from?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +            displayName: string;
where are these two coming from?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        | { status: "EMAIL_ALREADY_EXISTS_ERROR" }
not sure if this is the best way, cause if this error comes, but the user has already added a passkey in their browser, so it would get confusing

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        | { status: "EMAIL_ALREADY_EXISTS_ERROR" }
So instead, we should have this type of error in the part where we are generating a passkeyoption for the purpose of sign up?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +        | { status: "WRONG_CREDENTIALS_ERROR" }
Should we call this WRONG_CREDENTIALS_ERROR or something else?

2024-10-10 18:12 UTC, rishabhpoddar commented on lib/ts/recipe/passkey/types.ts
> +    consumeRecoverAccountToken(input: {
how will this work? LIke the user has to first generate a passkey options right and then call this function after?

2024-10-11 06:41 UTC, victorbojica commented on lib/ts/recipe/passkey/types.ts
> +export type TypeEmailPasswordEmailDeliveryInput = TypeEmailPasswordPasswordResetEmailDeliveryInput;
done

2024-10-11 06:41 UTC, victorbojica commented on lib/ts/recipe/passkey/types.ts
> +// todo update this ???
done

2024-10-11 06:42 UTC, victorbojica commented on lib/ts/recipe/passkey/types.ts
> +        password: string;
done

2024-10-11 06:42 UTC, victorbojica commented on lib/ts/recipe/passkey/types.ts
> +        session: SessionContainerInterface | undefined;
done

2024-10-16 15:35 UTC, closed without merging