feat: WebAuthN support
supertokens/supertokens-node pull request #966
Opened 2024-12-16 06:45 UTC by victorbojica

## Summary of change

(A few sentences about this PR)

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] If new thirdparty provider is added,
    -   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function.
    -   [ ] add an icon on the user management dashboard.
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `add-ts-no-check.js` file to include that
-   [ ] If added a new recipe / api interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If added a new recipe, then make sure to expose it inside the recipe folder present in the root of this repo. We also need to expose its types.
-   [ ] If added a new entry point, then make sure that it is importable by adding it to the `exports` in `package.json`

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2025-01-13 08:22 UTC, victorbojica commented on lib/ts/recipe/webauthn/types.ts
> +                        name: string;
this will be the email. @deepjyoti30-st

2025-03-06 21:29 UTC, porcellus commented on lib/ts/recipe/webauthn/api/recoverAccount.ts
> +    const credential = validateCredentialOrThrowError(requestBody.credential);
are these overrideable?

2025-03-06 21:37 UTC, porcellus commented on lib/ts/recipe/webauthn/api/implementation.ts
> +                displayName: "displayName" in props ? props.displayName : undefined,
what does this tertiary achieve?

2025-03-06 21:38 UTC, porcellus commented on lib/ts/recipe/webauthn/api/implementation.ts
> +                        "Cannot sign in / up due to security reasons. Please contact support. (ERR_CODE_013)",
These need to be separate error codes. Check the "last" error code we have and increment from there

2025-03-06 21:41 UTC, porcellus commented on lib/ts/recipe/webauthn/api/implementation.ts
> +                    "The credentials are incorrect. Please make sure you are using the correct credentials. (ERR_CODE_25)",
This is strange, is this required? The nvalid_X errors map to `SIGN_UP_NOT_ALLOWED` with a reason?

2025-03-06 21:42 UTC, porcellus commented on lib/ts/recipe/webauthn/api/implementation.ts
> +                // this isn't mandatory to
incomplete comment

2025-03-06 21:45 UTC, porcellus commented on lib/ts/recipe/webauthn/api/implementation.ts
> +                    "The credentials are incorrect. Please make sure you are using the correct credentials. (ERR_CODE_25)",
This isn't necessary.

2025-03-07 16:23 UTC, porcellus commented on lib/ts/recipe/webauthn/api/implementation.ts
> +                } else if (updateResponse.status === "INVALID_CREDENTIALS_ERROR") {
when does this happen?

2025-03-12 10:44 UTC, porcellus commented on test/test-server/src/index.ts
> +                        : undefined,
if the config is not present then these will not be logging. I think they should.

2025-03-12 12:17 UTC, porcellus requested changes

2025-03-12 12:17 UTC, porcellus commented on lib/ts/recipe/webauthn/recipe.ts
> -                    }
I think we should keep this part.

2025-03-12 12:17 UTC, porcellus commented on lib/ts/recipe/webauthn/api/recoverAccount.ts
> +    const credential = validateCredentialOrThrowError(requestBody.credential);
I guess this is ok since it only checks if it's defined or not.

2025-03-18 02:06 UTC, porcellus approved these changes

2025-03-18 02:07 UTC, merged